# Welcome to Numpy basics

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,37,7], np.int64)

In [3]:
myarr

array([ 3,  6, 37,  7], dtype=int64)

In [4]:
myarr[0]

3

In [5]:
myarr = np.array([[3,6,37,7]], np.int64)

In [6]:
myarr[0,1]

6

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
myarr[0,1] = 45

In [10]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

In [117]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [118]:
arr1.dtype

dtype('int32')

In [119]:
arr1 = np.array([[1,2.5,3],[4,5,6],[7,8,9]])

In [120]:
arr1.dtype

dtype('float64')

In [122]:
arr1 = np.array([[1,2.5,3],[4,5,6],[7,8,9]],dtype='int32')

In [123]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
arr1.dtype

dtype('int32')

# Array Creation : Conversion from other python structures


In [11]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({34,23,24})

array({24, 34, 23}, dtype=object)

In [17]:
np.array((2,3))

array([2, 3])

In [18]:
zeros = np.zeros((2,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.dtype

dtype('float64')

In [23]:
zeros = np.zeros((2,5),dtype = int)


In [24]:
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [125]:
ones = np.ones(6,)

In [126]:
ones

array([1., 1., 1., 1., 1., 1.])

In [26]:
rng = np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
lspace = np.linspace(1,50,10)  # linear spaced to each other from 1 to 50 and 10 elements

In [30]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [31]:
emp = np.empty((4,6)) #this will give an array of 4,6 filled with arbitary value so u can replace value (assign value) 

In [32]:
emp  

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 1.69121639e-306, 9.34613185e-307,
        1.24610383e-306, 1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        1.29060531e-306, 6.89805151e-307, 1.78020169e-306],
       [8.45559303e-307, 8.90071135e-308, 1.33511562e-306,
        8.90103560e-307, 1.42410974e-306, 8.90029544e-307]])

In [33]:
emp_like = np.empty_like(lspace) #creates an array of lspace size and assigns value same as lspace so you can assign new values amd resuse it  (this function used for efficency)

In [34]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [35]:
ide = np.identity(45) #gives identity matrix of 45 X 45

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
ide.shape

(45, 45)

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr = arr.reshape(3,33) #reshape arr to 3X33

In [42]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [45]:
arr = arr.ravel() #arr will become 1D array

In [46]:
arr.shape

(99,)

In [47]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [48]:
ar = np.array(x)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.sum(axis=0)

array([12,  8,  9])

In [52]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [53]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [55]:
ar.flat  # gives iterator

In [57]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [58]:
ar.ndim # no of dimensions

2

In [59]:
ar.size

9

In [60]:
ar.nbytes #total bytes consumed

36

In [63]:
one = np.array([1,3,4,634,2])

In [67]:
one.argmax()  #this is a function as i have put ()  # gives index of max value 

3

In [68]:
one.argmin()

0

In [69]:
one.argsort()  # it gives an array in which it will give indices in which org array must be sorted to give sorted array  (from smaller to larger numbers)

array([0, 4, 1, 2, 3], dtype=int64)

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
ar.argmin() #converts ar to 1D array and the find the index

8

In [72]:
ar.argmax()

6

In [73]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [74]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [75]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [76]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [77]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [78]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [95]:
ar.argmax()

6

# Matrix Operations

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [81]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [82]:
[324,46] + [25,86]   # above addition doesnt work with python lists 

[324, 46, 25, 86]

In [83]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [85]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [127]:
ar**ar2

array([[      1,       4,       3],
       [    256,       1,       0],
       [5764801,       1,       1]], dtype=int32)

In [128]:
2-ar

array([[ 1,  0, -1],
       [-2, -3,  2],
       [-5,  1,  2]])

In [89]:
ar2/ar

C:\Users\User\AppData\Local\Temp\ipykernel_11308\3416719587.py:1: RuntimeWarning: invalid value encountered in true_divide
  ar2/ar


array([[1.        , 1.        , 0.33333333],
       [1.        , 0.        , 1.        ],
       [1.14285714, 1.        ,        nan]])

In [146]:
ar2 > ar

array([[False, False, False],
       [False, False,  True],
       [ True, False, False]])

In [147]:
np.array_equal(ar,ar2)

False

In [90]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [91]:
ar.sum()

29

In [92]:
ar.max()

7

In [93]:
ar.min()

0

In [96]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [100]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [98]:
np.count_nonzero(ar)

8

In [102]:
np.nonzero(ar) # gives index of non zero elements in row and column format #zero will not be counted

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [103]:
ar[1,2]=0

nonzero first output
000
111
222

second output
012
012
012

In [104]:
np.nonzero(ar)  #also we are getting output in tuple

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

** checking that numpy array takes less space than python array (lists)

In [108]:
import sys

In [109]:
py_ar = [0,4,55,2]

In [110]:
np_ar = np.array(py_ar)

In [112]:
sys.getsizeof(1) * len(py_ar)

112

In [113]:
np_ar.itemsize * np_ar.size

16

In [114]:
np_ar.tolist()

[0, 4, 55, 2]

## Slicing

In [130]:
array2 = np.array([5,4,63,3,3,3])

In [131]:
array2[4:6]

array([3, 3])

In [135]:
arry = array2[4:6] # arr points to memory block wherw 3,3 stored in array2 location

In [136]:
arry[0] =9

In [137]:
array2 #array 2 gets updated even though we updated arr

array([ 5,  4, 63,  3,  9,  3])

**How to fix this issue**

In [139]:
arry = array2[4:6].copy()

In [142]:
arry[0] = 40

In [143]:
array2 #no changes in original array

array([ 5,  4, 63,  3,  9,  3])

In [144]:
array1 = np.array([[2,3,4,5],[5,6,7,9]])

In [145]:
array1[1,3]

9

# DOT Product

In [153]:
e = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
f = np.array([[4, 5], [1, 3], [8, 2]])

In [154]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
f

array([[4, 5],
       [1, 3],
       [8, 2]])

In [156]:
e.dot(f)  # matrix multiplication

array([[ 30,  17],
       [ 69,  47],
       [108,  77]])

# Statistics in Python

In [157]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
e.min()

1

In [159]:
e.max()

9

In [160]:
e.mean()

5.0

In [164]:
np.median(e)

5.0

In [165]:
e.std()

2.581988897471611

# Sorting

In [166]:
f

array([[4, 5],
       [1, 3],
       [8, 2]])

In [171]:
np.sort(f)

array([[1, 3],
       [2, 5],
       [4, 8]])

In [173]:
np.sort(f,axis=0)

array([[1, 3],
       [2, 5],
       [4, 8]])